# Generated by Django 5.2.5 on 2025-12-06 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoice_deleted_at_invoice_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='is_deleted',
        ),
    ]
