# Generated by Django 5.2.8 on 2025-12-11 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_remove_invoice_deleted_at_remove_invoice_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'permissions': [('can_view_all_invoices', 'User can access the entire billing and invoice history')]},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'permissions': [('can_manage_subscription', "User can change the project's subscription plan"), ('can_edit_billing_info', 'User can update payment methods and billing addresses')]},
        ),
    ]
