# Generated by Django 5.2.8 on 2026-01-09 05:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_invoice_options_alter_subscription_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='plan',
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'permissions': [('view_invoices', 'Can view billing history')]},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'permissions': [('view_subscription_plan', 'Can view current subscription details'), ('manage_subscription_plan', 'Can upgrade/downgrade resources (Owner/Scrum Master)'), ('pay_invoice', 'Can process billing payments')]},
        ),
        migrations.AddField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly'), ('FREE_TRIAL', 'Lakadi Free Trial')], default='MONTHLY', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='price_at_activation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='selected_storage_gb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='selected_testcases',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='selected_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('price_per_user', models.DecimalField(decimal_places=2, default=1.0, max_digits=6)),
                ('price_per_gb', models.DecimalField(decimal_places=2, default=1.0, max_digits=6)),
                ('price_per_testcase_unit', models.DecimalField(decimal_places=2, default=1.0, max_digits=6)),
                ('min_users', models.IntegerField(default=5)),
                ('min_storage_base', models.IntegerField(default=10)),
                ('storage_per_user_step', models.IntegerField(default=2)),
                ('testcase_unit_step', models.IntegerField(default=500)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pricing Configuration',
            },
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
    ]
