# Generated by Django 5.2.5 on 2026-01-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_remove_subscription_plan_alter_invoice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='paid',
            new_name='is_paid',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='external_ref',
        ),
        migrations.AddField(
            model_name='invoice',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly'), ('FREE_TRIAL', 'Free Trial')], default='MONTHLY', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='selected_storage_gb',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='selected_testcases',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='selected_users',
            field=models.IntegerField(default=5),
        ),
    ]
