# Generated by Django 5.2.5 on 2025-10-04 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('task', '0010_merge_20250930_1749'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='object_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(help_text='The user who wrote the comment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='task',
            field=models.ForeignKey(help_text='The task this comment belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='task.task'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(help_text='The content of the comment.'),
        ),
    ]
