# Generated by Django 5.2.5 on 2025-10-04 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_comment_content_type_remove_comment_object_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='task',
        ),
    ]
