# Generated by Django 5.2.5 on 2025-10-06 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_remove_comment_task'),
        ('task', '0012_remove_activity_type_activity_actor_activity_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='task',
            field=models.ForeignKey(help_text='The task this comment belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='task.task'),
        ),
    ]
