# Generated by Django 5.2.5 on 2025-10-16 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_attachment_deleted_at_attachment_is_deleted_and_more'),
        ('project', '0004_project_deleted_at_project_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(help_text='The project member who wrote the comment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_comments', to='project.projectmember'),
        ),
    ]
