# Generated by Django 5.2.5 on 2025-12-06 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_deleted',
        ),
    ]
