# Generated by Django 5.2.5 on 2025-11-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('SCRUM_MASTER', 'Scrum_Master'), ('DEVELOPER', 'Developer'), ('TESTER', 'Tester')], default='DEVELOPER', max_length=50),
        ),
    ]
