# Generated by Django 5.2.5 on 2025-12-06 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_teammember_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='team',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='is_deleted',
        ),
    ]
