# Generated by Django 5.2.8 on 2025-12-11 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_remove_team_deleted_at_remove_team_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'permissions': [('can_create_team', 'User can create new teams'), ('can_edit_team', 'User can update team name and description'), ('can_delete_team', 'User can delete teams'), ('can_view_all_teams', 'User can view all teams (Admin view)')]},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'permissions': [('can_invite_team_members', 'User can invite new members to the team'), ('can_remove_team_members', 'User can remove members from the team'), ('can_manage_team_roles', 'User can change the role of existing team members')]},
        ),
    ]
