# Generated by Django 5.2.8 on 2025-12-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_alter_team_options_alter_teammember_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('SCRUM_MASTER', 'Scrum_Master'), ('DEVELOPER', 'Developer'), ('TESTER', 'Tester'), ('VIEWER', 'Viewer')], default='DEVELOPER', max_length=50),
        ),
    ]
