# Generated by Django 5.2 on 2026-01-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_protected',
            field=models.BooleanField(default=False),
        ),
    ]
