# Generated by Django 5.2 on 2025-11-26 05:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        ('task', '0019_epic_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['path', 'id']},
        ),
        migrations.RemoveField(
            model_name='pageversion',
            name='content',
        ),
        migrations.AddField(
            model_name='pageversion',
            name='comment',
            field=models.CharField(blank=True, help_text='Optional edit note / summary of the change.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pageversion',
            name='content_html',
            field=models.TextField(blank=True, help_text='Sanitized HTML rendering of the content for display/search.', null=True),
        ),
        migrations.AddField(
            model_name='pageversion',
            name='content_json',
            field=models.JSONField(blank=True, help_text='Structured JSON document if using a rich editor like TipTap.', null=True),
        ),
        migrations.AddField(
            model_name='pageversion',
            name='content_markdown',
            field=models.TextField(blank=True, help_text='Raw Markdown source from the editor (if using markdown).', null=True),
        ),
        migrations.AddField(
            model_name='pageversion',
            name='editor_format',
            field=models.CharField(choices=[('markdown', 'Markdown'), ('html', 'HTML'), ('json', 'JSON (structured editor)')], default='markdown', help_text='Format of the canonical source content.', max_length=20),
        ),
        migrations.AlterField(
            model_name='page',
            name='path',
            field=models.TextField(help_text="Path within the project docs tree, e.g. 'architecture/api-design'. Used for ordering and building the sidebar tree."),
        ),
        migrations.AlterField(
            model_name='pageversion',
            name='version',
            field=models.PositiveIntegerField(help_text='Monotonically increasing version number (1, 2, 3, ...).'),
        ),
        migrations.CreateModel(
            name='PageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(help_text='Uploaded file (image, document, etc.)', upload_to='page_attachments/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.PositiveBigIntegerField(blank=True, help_text='Size in bytes (for limits & display).', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='pages.page')),
                ('page_version', models.ForeignKey(blank=True, help_text='The version where this attachment was first added (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='pages.pageversion')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskPageLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, help_text='Optional note about why this task is linked to this page.', max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_page_links', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_links', to='pages.page')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_links', to='task.task')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('task', 'page')},
            },
        ),
    ]
