# Generated by Django 5.2.5 on 2025-12-06 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_page_options_remove_pageversion_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='page',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='pageattachment',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='pageattachment',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='pageversion',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='pageversion',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='taskpagelink',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='taskpagelink',
            name='is_deleted',
        ),
    ]
