# Generated by Django 5.2.8 on 2025-12-11 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_page_deleted_at_remove_page_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['path', 'id'], 'permissions': [('can_create_page', 'User can create new documentation pages'), ('can_edit_page', 'User can update page title and hierarchy'), ('can_delete_page', 'User can delete documentation pages'), ('can_archive_page', 'User can archive or restore pages'), ('can_view_pages', 'User can view documentation pages')]},
        ),
        migrations.AlterModelOptions(
            name='pageattachment',
            options={'ordering': ['-created_at'], 'permissions': [('can_upload_attachment', 'User can upload files to pages'), ('can_delete_attachment', 'User can remove attached files')]},
        ),
        migrations.AlterModelOptions(
            name='pageversion',
            options={'ordering': ['-version'], 'permissions': [('can_edit_page_content', 'User can update content (create new versions)'), ('can_view_page_history', 'User can view historical versions of a page'), ('can_revert_page_version', 'User can revert page to a previous version')]},
        ),
        migrations.AlterModelOptions(
            name='taskpagelink',
            options={'ordering': ['-created_at'], 'permissions': [('can_link_pages_to_tasks', 'User can link/unlink pages to tasks')]},
        ),
    ]
