# Generated by Django 5.2.5 on 2025-09-24 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('testCase', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testcase',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='MEDIUM', max_length=20),
        ),
        migrations.AddField(
            model_name='testcase',
            name='test_type',
            field=models.CharField(choices=[('FUNCTIONAL', 'Functional'), ('SMOKE', 'Smoke'), ('REGRESSION', 'Regression'), ('PERFORMANCE', 'Performance'), ('SECURITY', 'Security')], default='FUNCTIONAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='expected_result',
            field=models.TextField(help_text='The expected outcome after executing the steps.'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='project.project'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='steps',
            field=models.TextField(help_text='Step-by-step instructions to execute the test.'),
        ),
    ]
