# Generated by Django 5.2.5 on 2025-10-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testCase', '0002_testcase_assignee_testcase_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationscript',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='automationscript',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testcase',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
