# Generated by Django 5.2.8 on 2025-12-11 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testCase', '0002_testtemplate_templatestep_qatestcase_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='module',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='qatestcase',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='qatestcase',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='testplan',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='testplan',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='testrun',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='testrun',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='testsuite',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='testsuite',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='testtemplate',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='testtemplate',
            name='is_deleted',
        ),
    ]
