# Generated by Django 5.2.5 on 2025-12-06 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testCase', '0003_automationscript_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automationscript',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='automationscript',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='is_deleted',
        ),
    ]
