# Generated by Django 5.2.8 on 2025-12-11 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testCase', '0003_remove_module_deleted_at_remove_module_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='environment',
            options={'permissions': [('can_manage_environments', 'User can create and edit test environments')]},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ('project', 'parent__id', 'name'), 'permissions': [('can_create_module', 'User can create new test modules'), ('can_edit_module', 'User can edit module details'), ('can_delete_module', 'User can delete modules')]},
        ),
        migrations.AlterModelOptions(
            name='qatestcase',
            options={'permissions': [('can_create_testcase', 'User can create new test case definitions'), ('can_edit_testcase', 'User can edit test case details'), ('can_run_testcases', 'User can run a test and report the pass/fail status'), ('can_link_test_to_task', 'User can link a test case to a requirement (Task)'), ('can_manage_test_steps', 'User can create and update Test Steps'), ('can_delete_testcase', 'User can delete test cases')]},
        ),
        migrations.AlterModelOptions(
            name='testexecution',
            options={'permissions': [('can_update_execution_status', 'User can update the status of a specific test execution')]},
        ),
        migrations.AlterModelOptions(
            name='testplan',
            options={'permissions': [('can_create_test_plan', 'User can create new test plans'), ('can_edit_test_plan', 'User can edit test plans'), ('can_delete_test_plan', 'User can delete test plans')]},
        ),
        migrations.AlterModelOptions(
            name='testrun',
            options={'permissions': [('can_create_test_run', 'User can create new test runs'), ('can_execute_test_run', 'User can execute/start test runs'), ('can_delete_test_run', 'User can delete test runs')]},
        ),
        migrations.AlterModelOptions(
            name='testsuite',
            options={'permissions': [('can_create_suite', 'User can create test suites'), ('can_edit_suite', 'User can edit test suites'), ('can_delete_suite', 'User can delete test suites')]},
        ),
        migrations.AlterModelOptions(
            name='testtemplate',
            options={'permissions': [('can_manage_test_templates', 'User can create, edit, and delete test templates')]},
        ),
    ]
