# Generated by Django 5.2.5 on 2025-12-28 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testCase', '0004_alter_environment_options_alter_module_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qatestcase',
            name='suite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='testCase.testsuite'),
        ),
    ]
