# Generated by Django 5.2.5 on 2026-01-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testCase', '0005_alter_qatestcase_suite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qatestcase',
            name='labels',
            field=models.CharField(choices=[('FUNCTIONAL', 'Functional'), ('SMOKE', 'Smoke'), ('REGRESSION', 'Regression'), ('NEGATIVE', 'Negative'), ('SECURITY', 'Security'), ('VALIDATION', 'Validation'), ('EDGE', 'Edge Case'), ('PERFORMANCE', 'Performance'), ('INTEGRATION', 'Integration'), ('USABILITY', 'Usability')], default='FUNCTIONAL', max_length=20),
        ),
    ]
