# Generated by Django 5.2.5 on 2026-01-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testCase', '0006_alter_qatestcase_labels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teststep',
            options={'ordering': ['order'], 'permissions': [('can_manage_step', 'User can create, edit and delete testcase steps ')]},
        ),
        migrations.RemoveField(
            model_name='qatestcase',
            name='suite',
        ),
        migrations.AddField(
            model_name='testsuite',
            name='cases',
            field=models.ManyToManyField(related_name='suites', to='testCase.qatestcase'),
        ),
    ]
