# Generated by Django 5.2.5 on 2026-01-09 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_project_options'),
        ('testCase', '0007_alter_teststep_options_remove_qatestcase_suite_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testsuite',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='suites', to='project.project'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='testsuite',
            name='module',
        ),
    ]
