# Generated by Django 5.2.5 on 2026-01-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testCase', '0008_alter_testsuite_unique_together_testsuite_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuite',
            name='last_executed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived'), ('NOT_EXECUTED', 'Not_executed')], default='NOT_EXECUTED', max_length=20),
        ),
    ]
