# Generated by Django 5.2.5 on 2026-01-23 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testCase', '0009_testsuite_last_executed_on_testsuite_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ('project', 'parent__id', 'name'), 'permissions': [('can_create_module', 'User can create new test modules'), ('can_edit_module', 'User can edit module details'), ('can_delete_module', 'User can delete modules'), ('can_view_all_module', 'User can view all modules in a project')]},
        ),
        migrations.AlterModelOptions(
            name='qatestcase',
            options={'permissions': [('can_create_testcase', 'User can create new test case definitions'), ('can_edit_testcases', 'User can edit test case details'), ('can_run_testcases', 'User can run a test and report the pass/fail status'), ('can_manage_test_steps', 'User can create and update Test Steps'), ('can_delete_testcase', 'User can delete test cases'), ('can_view_all_testcases', 'User can view all testcase of a module'), ('can_edit_parent_module', 'can change module of a testcase')]},
        ),
        migrations.AlterModelOptions(
            name='templatestep',
            options={'ordering': ['order'], 'permissions': [('can_create_template_steps', 'User can create new step for a template'), ('can_edit_template_steps', 'User can edit steps of a template'), ('can_delete_template_steps', 'User can delete steps'), ('can_view_all_template_steps', 'User can view all steps of a template of a project')]},
        ),
        migrations.AlterModelOptions(
            name='teststep',
            options={'ordering': ['order'], 'permissions': [('can_manage_step', 'User can create, edit and delete testcase steps '), ('can_create_steps', 'User can create test steps'), ('can_edit_steps', 'User can edit test steps'), ('can_delete_steps', 'User can delete test steps'), ('can_view_all_steps', 'User can view all steps of a testcase')]},
        ),
        migrations.AlterModelOptions(
            name='testsuite',
            options={'permissions': [('can_create_suite', 'User can create test suites'), ('can_edit_suite', 'User can edit test suites'), ('can_delete_suite', 'User can delete test suites'), ('can_view_all_suites', 'User can view all suits of a project'), ('can_add_testcases', 'User can add testcasses to suit')]},
        ),
        migrations.AlterModelOptions(
            name='testtemplate',
            options={'permissions': [('can_create_testTemplate', 'User can create new template for testcase'), ('can_edit_testTemplate', 'User can edit template details'), ('can_delete_testTemplate', 'User can delete template'), ('can_view_all_testTemplate', 'User can view all template in a project')]},
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='testtemplate',
            unique_together=set(),
        ),
    ]
