# Generated by Django 5.2.5 on 2026-01-31 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_project_organization'),
        ('testCase', '0010_alter_module_options_alter_qatestcase_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qatestcase',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='project.project'),
        ),
    ]
