# Generated by Django 5.2.5 on 2025-09-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('LOWEST', 'Lowest'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('HIGHEST', 'Highest')], default='MEDIUM', max_length=20),
        ),
    ]
