# Generated by Django 5.2.5 on 2025-09-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='activity_history',
            field=models.JSONField(blank=True, default=list, help_text='Stores a log of all activities like history and work logs on this task.', null=True),
        ),
    ]
