# Generated by Django 5.2.5 on 2025-09-24 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_task_activity_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='activity_history',
        ),
    ]
