# Generated by Django 5.2.5 on 2025-09-30 12:16
from django.db import migrations

# A list of default statuses.
# we can easily add, remove, or change these as needed.
DEFAULT_STATUSES = [
    "To Do",
    "In Progress",
    "In Review",
    "Done",
    "Testing",
]

def create_default_statuses(apps, schema_editor):
    """
    This function is executed when the migration is applied.
    """
    # We get the model from the versioned app registry;
    # it's important to not import the model directly.
    Status = apps.get_model('task', 'Status')
    
    # We use a loop to create a Status object for each title in our list.
    for status_title in DEFAULT_STATUSES:
        Status.objects.create(title=status_title)

def revert_default_statuses(apps, schema_editor):
    """
    This function is executed when the migration is un-applied (reverted).
    It should contain the logic to reverse the changes made in the forward function.
    """
    Status = apps.get_model('task', 'Status')
    
    # We find and delete the statuses we created.
    Status.objects.filter(title__in=DEFAULT_STATUSES).delete()


class Migration(migrations.Migration):

    # This migration depends on the migration that created the Status model.
    # Replace '0001_initial' with the actual name of your first migration file.
    dependencies = [
        ('task', '0001_initial'), 
    ]

    operations = [
        # The migrations.RunPython operation calls our function.
        # We also provide the reverse function for when we want to rollback.
        migrations.RunPython(create_default_statuses, reverse_code=revert_default_statuses),
    ]