# Generated by Django 5.2.5 on 2025-09-30 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_remove_task_activity_history'),
        ('task', '0009_create_default_statuses'),
    ]

    operations = [
    ]
