# Generated by Django 5.2.5 on 2025-10-04 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_merge_20250930_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['order'], 'verbose_name_plural': 'Statuses'},
        ),
        migrations.AddField(
            model_name='status',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of the column on the board'),
        ),
    ]
