# Generated by Django 5.2 on 2025-10-17 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_task_completed_at_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='epic',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='epic',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
