# Generated by Django 5.2.5 on 2025-10-21 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0016_alter_epic_status_alter_task_epic_alter_task_sprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epic',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epics', to='task.status'),
        ),
    ]
