# Generated by Django 5.2 on 2025-11-01 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0017_alter_epic_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epic',
            name='status',
        ),
    ]
