# Generated by Django 5.2 on 2025-11-01 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0018_remove_epic_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='epic',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epics', to='task.status'),
        ),
    ]
