# Generated by Django 5.2.5 on 2025-12-01 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0020_task_form_data_formtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formtemplate',
            name='task_type',
            field=models.CharField(choices=[('BUG', 'Bug'), ('FEATURE', 'Feature'), ('IMPROVEMENT', 'Improvement')], default='FEATURE', max_length=20),
        ),
    ]
