# Generated by Django 5.2.5 on 2025-12-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_projectmember_role_projectinvitation'),
        ('task', '0021_alter_formtemplate_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='form_templates_assigned', to='project.projectmember'),
        ),
    ]
