# Generated by Django 5.2.5 on 2025-12-06 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0024_sprint_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='epic',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='epic',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='formtemplate',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='formtemplate',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='sprint',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='sprint',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='status',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='status',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='task',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='is_deleted',
        ),
    ]
