# Generated by Django 5.2.8 on 2025-12-11 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0025_remove_activity_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='epic',
            options={'permissions': [('can_create_epic', 'User can create new Epics'), ('can_edit_epic', 'User can modify Epic details'), ('can_delete_epic', 'User can delete Epics')]},
        ),
        migrations.AlterModelOptions(
            name='sprint',
            options={'permissions': [('can_create_sprint', 'User can create a new sprint'), ('can_start_sprint', 'User can activate an upcoming sprint'), ('can_end_sprint', 'User can close an active sprint'), ('can_move_to_backlog', 'User can move items between a sprint and the backlog'), ('can_edit_sprint', 'User can edit sprint details')]},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['order'], 'permissions': [('can_create_status', 'User can create new Kanban statuses/columns'), ('can_edit_status', 'User can rename or update existing statuses'), ('can_delete_status', 'User can delete a status column'), ('can_reorder_status', 'User can change the order of status columns')], 'verbose_name_plural': 'Statuses'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': [('can_create_task', 'User can create new Tasks/Tickets/Bugs'), ('can_edit_tasks', 'User can edit the title, description, and fields of any task'), ('can_edit_task_own', 'User can only edit tasks they reported/created'), ('can_assign_task', 'User can assign a task to any other project member or himself'), ('can_change_status', 'User can change the status of a task'), ('can_change_priority', 'User can change task priority'), ('can_add_comment', 'User can add comments to a task'), ('can_manage_attachments', 'User can add/remove attachments from a task'), ('can_delete_task', 'User can permanently delete tasks')]},
        ),
    ]
