# Generated by Django 5.2.8 on 2025-12-11 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0026_alter_epic_options_alter_sprint_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formtemplate',
            options={'permissions': [('can_create_form_template', 'User can design new form templates'), ('can_edit_form_template', 'User can modify form structures'), ('can_delete_form_template', 'User can delete form templates'), ('can_submit_form', 'User can submit entries via forms')]},
        ),
        migrations.AlterModelOptions(
            name='goal',
            options={'permissions': [('can_create_goal', 'User can define new project goals'), ('can_edit_goal', 'User can update goal progress/status'), ('can_delete_goal', 'User can remove goals'), ('can_view_goals', 'User can view project goals')]},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'permissions': [('can_create_tag', 'User can create new tags'), ('can_delete_tag', 'User can delete tags'), ('can_manage_tags', 'User can rename or merge tags')]},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': [('can_create_task', 'User can create new Tasks/Tickets/Bugs'), ('can_edit_tasks', 'User can edit the title, description, and fields of any task'), ('can_edit_task_own', 'User can only edit tasks they reported/created'), ('can_assign_task', 'User can assign a task to any other project member or himself'), ('can_change_status', 'User can change the status of a task'), ('can_change_priority', 'User can change task priority'), ('can_add_comment', 'User can add comments to a task'), ('can_manage_attachments', 'User can add/remove attachments from a task'), ('can_delete_task', 'User can permanently delete tasks'), ('can_view_all_tasks', 'User can view tasks in the project'), ('can_set_due_date', 'User can set or modify task due dates'), ('can_edit_story_points', 'User can set or change story point estimates'), ('can_link_tasks', 'User can link tasks to other tasks')]},
        ),
    ]
