# Generated by Django 5.2.5 on 2025-09-22 05:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.GenericIPAddressField(blank=True, null=True)),
                ('updated_by', models.GenericIPAddressField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ONGOING', 'Ongoing'), ('DELAYED', 'Delayed'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='PLANNED', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.GenericIPAddressField(blank=True, null=True)),
                ('updated_by', models.GenericIPAddressField(blank=True, null=True)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('PROJECT_MANAGER', 'Project Manager'), ('DEVELOPER', 'Developer'), ('TESTER', 'Tester')], max_length=20)),
            ],
        ),
    ]
