# Generated by Django 5.2.5 on 2025-09-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'planned'), ('ONGOING', 'ongoing'), ('DELAYED', 'delayed'), ('COMPLETED', 'completed'), ('ARCHIVED', 'archived')], default='PLANNED', max_length=20),
        ),
    ]
