# Generated by Django 5.2.5 on 2025-10-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_deleted_at_project_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmember',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('DEVELOPER', 'Developer'), ('TESTER', 'Tester')], max_length=20),
        ),
    ]
