# Generated by Django 5.2.5 on 2025-12-06 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_projectmember_role_projectinvitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='projectinvitation',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='projectinvitation',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='projectmember',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='projectmember',
            name='is_deleted',
        ),
    ]
