# Generated by Django 5.2.8 on 2025-12-11 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_remove_project_deleted_at_remove_project_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('can_create_project', 'User can create a brand new project instance'), ('can_edit_project_details', 'User can change project name, key, and description'), ('can_archive_project', 'User can archive or restore the project'), ('can_manage_project_members', 'User can add, remove, and change the roles of other users'), ('can_manage_workflows', 'User can create and edit custom workflow schemes'), ('can_have_full_project_access', 'User can do any changes on project including task, sprint, epic etc'), ('can_delete_project', 'User can delete a project')]},
        ),
        migrations.AlterModelOptions(
            name='projectinvitation',
            options={'ordering': ['-created_at'], 'permissions': [('can_invite_member', 'User can send project invitations'), ('can_view_invitations', 'User can view sent invitations'), ('can_cancel_invitation', 'User can revoke/cancel pending invitations')]},
        ),
    ]
