# Generated by Django 5.2.5 on 2025-12-17 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('can_create_project', 'User can create a brand new project instance'), ('can_edit_project_details', 'User can change project name, key, and description'), ('can_archive_project', 'User can archive or restore the project'), ('can_manage_project_members', 'User can add, remove, and change the roles of other users'), ('can_manage_workflows', 'User can create and edit custom workflow schemes'), ('can_delete_project', 'User can delete a project'), ('can_view_project_summary', 'can_view_project_settings')]},
        ),
    ]
