# Generated by Django 5.2.5 on 2025-11-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('SCRUM_MASTER', 'Scrum_Master'), ('DEVELOPER', 'Developer'), ('TESTER', 'Tester')], default='OWNER', max_length=50),
        ),
    ]
