# Generated by Django 5.2.5 on 2025-12-12 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_create_system_users', 'User can add new users to the entire system'), ('can_view_all_users', 'User can see the list of all users across all projects'), ('can_reset_passwords', 'User can force a password reset for other users'), ('can_delete_users', 'User can delete users'), ('can_edit_users_info', "User can edit other users' information"), ('can_invite_users', 'User can invite new users via email')]},
        ),
    ]
